version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes: 
      - ./v2ray/config.json:/etc/v2ray/config.json
      - ./v2ray/log:/var/log/v2ray
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose: 
      - "17995"
  caddy:
    image: caddy
    container_name: caddy
    volumes: 
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/log/caddy:/var/log/caddy
      - ./caddy/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - "443:443"